import Foundation

enum PhotoLibrary {
    static let all: [Photo] = [
        Photo(assetName: "F1Sint-Michielshelling", title: "Sint Michielshelling", collection: .featured),
        Photo(assetName: "F2GSP", title: "Gent-Sint-Pieters", collection: .featured),
        Photo(assetName: "F3Dampoort", title: "Dampoort", collection: .featured),
        Photo(assetName: "F4GSP2", title: "GSP2", collection: .featured),
        Photo(assetName: "F5Korenmarkt", title: "Korenmarkt", collection: .featured),
        Photo(assetName: "F6Groot-Begijnhof", title: "Groot Begijnhof", collection: .featured),
        Photo(assetName: "F7DokNoord", title: "Dok Noord", collection: .featured),
        Photo(assetName: "F8Belfort", title: "Belfort", collection: .featured),
        Photo(assetName: "F9Dampoort", title: "Dampoort", collection: .featured),
        Photo(assetName: "F10Groot-Begijnhof", title: "Groot Begijnhof", collection: .featured),
        Photo(assetName: "F11OudeDokken", title: "Oude Dokken", collection: .featured),
        Photo(assetName: "F12OudeDokken", title: "Oude Dokken", collection: .featured),
        Photo(assetName: "F13SintAmandsberg", title: "Sint Amandsberg", collection: .featured),
        Photo(assetName: "F14GSP", title: "Gent-Sint-Pieters", collection: .featured),
        Photo(assetName: "F15SintMichielsbrug", title: "Sint Michielsbrug", collection: .featured),
        Photo(assetName: "F16SintMichielsbrug", title: "Sint Michielsbrug", collection: .featured),
        Photo(assetName: "F17Sint-Amandsberg", title: "Sint Amandsberg", collection: .featured),
        Photo(assetName: "N1OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N2OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N3OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N4OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N5OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N6OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N7OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N8OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N9OudeDokken", title: "Oude Dokken", collection: .new),
        Photo(assetName: "N10Korenmarkt", title: "Korenmarkt", collection: .new),
        Photo(assetName: "N11Groot-Begijnhof", title: "Groot Begijnhof", collection: .new),
        Photo(assetName: "N12GSP", title: "Gent-Sint-Pieters", collection: .new),
        Photo(assetName: "N13GSP", title: "Gent-Sint-Pieters", collection: .new),
        Photo(assetName: "N14Sint-Michielshelling", title: "Sint Michielshelling", collection: .new),
        Photo(assetName: "N15Sint-Pieterskerk", title: "Sint Pieterskerk", collection: .new),
        Photo(assetName: "N16Groot-Begijnhof", title: "Groot Begijnhof", collection: .new),
        Photo(assetName: "N17SintAmandsberg", title: "Sint Amandsberg", collection: .new),
        Photo(assetName: "N18Groot-Begijnhof", title: "Groot Begijnhof", collection: .new),
        Photo(assetName: "L1OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L2OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L3OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L4OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L5OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L6OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L7OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L8OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L9OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L10Dampoort", title: "Dampoort", collection: .landscape),
        Photo(assetName: "L11GSP", title: "Gent-Sint-Pieters", collection: .landscape),
        Photo(assetName: "L12GSP", title: "Gent-Sint-Pieters", collection: .landscape),
        Photo(assetName: "L13Korenmarkt", title: "Korenmarkt", collection: .landscape),
        Photo(assetName: "L14Graslei", title: "Graslei", collection: .landscape),
        Photo(assetName: "L15GSP", title: "Gent-Sint-Pieters", collection: .landscape),
        Photo(assetName: "L16GSP", title: "Gent-Sint-Pieters", collection: .landscape),
        Photo(assetName: "L17GrootBegijnhof", title: "Groot Begijnhof", collection: .landscape),
        Photo(assetName: "L18Tweebruggen", title: "Tweebruggen", collection: .landscape),
        Photo(assetName: "L19Houtdok", title: "Houtdok", collection: .landscape),
        Photo(assetName: "L20Houtdok", title: "Houtdok", collection: .landscape),
        Photo(assetName: "L21Houtdok", title: "Houtdok", collection: .landscape),
        Photo(assetName: "L22Azaleapark", title: "Azaleapark", collection: .landscape),
        Photo(assetName: "L23OudeDokken", title: "Oude Dokken", collection: .landscape),
        Photo(assetName: "L24GSP", title: "Gent-Sint-Pieters", collection: .landscape),
        Photo(assetName: "L25GrootBegijnhof", title: "Groot Begijnhof", collection: .landscape),
        Photo(assetName: "P1GrootBegijnhof", title: "Groot Begijnhof", collection: .portrait),
        Photo(assetName: "P2SintAmandsberg", title: "Sint Amandsberg", collection: .portrait),
        Photo(assetName: "P3Sint-Pieterskerk", title: "Sint Pieterskerk", collection: .portrait),
        Photo(assetName: "P4Sint-Michielshelling", title: "Sint Michielshelling", collection: .portrait),
        Photo(assetName: "P5GSP", title: "Gent-Sint-Pieters", collection: .portrait),
        Photo(assetName: "P6GSP", title: "Gent-Sint-Pieters", collection: .portrait),
        Photo(assetName: "P7GrootBegijnhof", title: "Groot Begijnhof", collection: .portrait),
        Photo(assetName: "P8Korenmarkt", title: "Korenmarkt", collection: .portrait),
        Photo(assetName: "P9Sint-Jacobs", title: "Sint Jacobs", collection: .portrait),
        Photo(assetName: "P10Dok-Noord", title: "Dok Noord", collection: .portrait),
        Photo(assetName: "P11Dampoort", title: "Dampoort", collection: .portrait),
        Photo(assetName: "P12Dampoort", title: "Dampoort", collection: .portrait),
        Photo(assetName: "P13Belfort", title: "Belfort", collection: .portrait),
        Photo(assetName: "V1Bisdomkaai", title: "Bisdomkaai", collection: .vault),
        Photo(assetName: "V2Afrikalaan", title: "Afrikalaan", collection: .vault),
        Photo(assetName: "V3Banierpark", title: "Banierpark", collection: .vault),
        Photo(assetName: "V4DeKrook", title: "De Krook", collection: .vault),
        Photo(assetName: "V5Braeckmanlaan", title: "Braeckmanlaan", collection: .vault),
        Photo(assetName: "V6Coyensdanspark", title: "Coyensdanspark", collection: .vault),
        Photo(assetName: "V7Dampoort", title: "Dampoort", collection: .vault),
        Photo(assetName: "V8GrootVleeshuis", title: "Groot Vleeshuis", collection: .vault),
        Photo(assetName: "V9SecretPassageway", title: "Secret Passageway", collection: .vault),
        Photo(assetName: "V10GSP", title: "Gent-Sint-Pieters", collection: .vault),
        Photo(assetName: "V11Dampoort", title: "Dampoort", collection: .vault),
        Photo(assetName: "V12E40DrongenNoord", title: "E40Drongen Noord", collection: .vault),
        Photo(assetName: "V13FlandersExpo", title: "Flanders Expo", collection: .vault),
        Photo(assetName: "V14GrootBegijnhof", title: "Groot Begijnhof", collection: .vault),
        Photo(assetName: "V15GentDampoort", title: "Gent Dampoort", collection: .vault),
        Photo(assetName: "V16GSP", title: "Gent-Sint-Pieters", collection: .vault),
        Photo(assetName: "V17LVW", title: "Land van Waaslaan", collection: .vault),
        Photo(assetName: "V18LVW", title: "Land van Waaslaan", collection: .vault),
        Photo(assetName: "V19GrootBegijnhof", title: "Groot Begijnhof", collection: .vault),
        Photo(assetName: "V20GrootBegijnhof", title: "Groot Begijnhof", collection: .vault),
        Photo(assetName: "V21GrootBegijnhof", title: "Groot Begijnhof", collection: .vault),
        Photo(assetName: "V22GrootBegijnhof", title: "Groot Begijnhof", collection: .vault),
    ]

    static let portfolio = all.filter { $0.collection != .vault }
    static let vault = all.filter { $0.collection == .vault }
}
